"use client";

import React, { useState } from "react";
import { FileText, Folder, Upload, Search, Download, Trash2, Code, FileCode } from "lucide-react";
import { Button } from "@/components/ui/Button";
import { Badge } from "@/components/ui/Badge";

export const FilesView: React.FC = () => {
  const [search, setSearch] = useState("");

  const files = [
    { name: "page.tsx", type: "TypeScript React", size: "19.2 KB", modified: "10m ago" },
    { name: "AuthContext.tsx", type: "TypeScript Context", size: "4.8 KB", modified: "1h ago" },
    { name: "ai-orchestrator.rs", type: "Rust Source", size: "12.4 KB", modified: "1d ago" },
    { name: "tailwind.config.ts", type: "TypeScript Config", size: "2.1 KB", modified: "2d ago" },
  ];

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-extrabold text-white flex items-center gap-2">
            <FileText className="h-6 w-6 text-pink-400" />
            Workspace Files & Assets
          </h1>
          <p className="text-xs text-text-secondary">
            Browse and manage files generated by subagents and user uploaded code.
          </p>
        </div>

        <Button variant="glow" icon={<Upload className="h-4 w-4" />}>
          Upload File
        </Button>
      </div>

      <div className="p-4 rounded-2xl bg-surface/70 border border-border space-y-4">
        <div className="relative">
          <Search className="absolute left-3.5 top-3 h-4 w-4 text-text-secondary" />
          <input
            type="text"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            placeholder="Search workspace files..."
            className="w-full pl-10 pr-4 py-2.5 rounded-xl glass-input text-xs"
          />
        </div>

        <div className="space-y-2">
          {files.map((file, idx) => (
            <div key={idx} className="p-3.5 rounded-xl bg-surface-subtle border border-border flex items-center justify-between hover:border-primary/40 transition-colors">
              <div className="flex items-center gap-3">
                <FileCode className="h-5 w-5 text-primary-light" />
                <div>
                  <div className="text-xs font-bold text-white">{file.name}</div>
                  <div className="text-[10px] text-text-secondary">{file.type} &bull; {file.size}</div>
                </div>
              </div>

              <div className="flex items-center gap-3 text-xs text-text-secondary font-mono">
                <span>{file.modified}</span>
                <button className="p-1.5 rounded-lg bg-surface border border-border hover:text-white">
                  <Download className="h-3.5 w-3.5" />
                </button>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};
